# Generated by Django 4.1 on 2024-07-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0002_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
