# Generated by Django 4.1 on 2024-07-05 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0003_alter_education_description_alter_education_end_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Progam_skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(max_length=100)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cv.profile"
                    ),
                ),
            ],
        ),
    ]
