# Generated by Django 4.1 on 2024-07-05 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0004_progam_skill"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Progam_skill",
            new_name="ProgramSkill",
        ),
    ]
