# Generated by Django 4.1 on 2024-07-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0005_rename_progam_skill_programskill"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="instagram",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
