# Generated by Django 4.1 on 2024-07-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0006_profile_instagram_alter_experience_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="facebook",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="github",
            field=models.URLField(blank=True, null=True),
        ),
    ]
