# Generated by Django 4.1 on 2024-07-05 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0007_profile_facebook_profile_github"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("image1", models.ImageField(upload_to="projects/")),
                ("image2", models.ImageField(upload_to="projects/")),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cv.profile"
                    ),
                ),
            ],
        ),
    ]
