# Generated by Django 4.1 on 2024-07-05 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0008_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="image2",
        ),
    ]
